language: node_js
node_js:
  - "6"
env:
  global:
  - USER="sagarpanda"
  - REPO="music-box"
  - GH_REPO="github.com/${USER}/${REPO}.git"
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: "public"
  github_token: $GITHUB_TOKEN
  commit_message: 'Travis CI'
  on:
    branch: master
