language: node_js
node_js:
  - "6"
script:
  - npm run build
  - git subtree split --prefix public -b gh-pages
  - git remote add origin https://${GITHUB_TOKEN}@github.com/sagarpanda/music-box.git
  - git push -f origin gh-pages:gh-pages
  - git branch -D gh-pages
